import { useAuth } from '@/features/auth/AuthContext';
import { useForm, ValidationError } from '@formspree/react';
import { Lightbulb, Send } from 'lucide-react';

export default function FeedbackPage() {
  const FORMSFREE_ID = import.meta.env.VITE_FORMSPREE_ID;
  const { user } = useAuth();
  const [state, handleSubmit] = useForm(FORMSFREE_ID);
  const email = user?.email ?? '';

  if (state.succeeded) {
    return <div className="mx-auto max-w-3xl border border-emerald-400/20 bg-emerald-400/[0.06] p-8"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-300">Message sent</p><h1 className="mt-3 text-3xl font-semibold text-white">Thanks for helping improve Yolnoma.</h1><p className="mt-3 text-sm leading-6 text-white/55">Your idea or bug report has been received.</p></div>;
  }

  return <div className="mx-auto max-w-3xl pb-16"><div className="border-b border-white/[0.08] pb-8"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[var(--accent)]">Community feedback</p><h1 className="mt-3 font-serif text-4xl font-medium text-white md:text-5xl">Help shape Yolnoma</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/45">Found a bug or have an idea? Send it directly to the Yolnoma team. Your profile email is attached automatically.</p></div><form onSubmit={handleSubmit} className="mt-8 border border-white/[0.08] bg-[#111109] p-6 shadow-xl md:p-8"><div className="flex items-start gap-4 border-b border-white/[0.08] pb-6"><span className="flex h-10 w-10 shrink-0 items-center justify-center bg-[var(--accent-glow)] text-[var(--accent)]"><Lightbulb size={19} /></span><div><h2 className="font-semibold text-white">Ideas and bug reports</h2><p className="mt-1 text-xs leading-5 text-white/40">Please describe what happened and what you would like to see improved.</p></div></div><div className="mt-6"><label htmlFor="feedback-email" className="mb-2 block text-xs font-medium text-white/65">Email address</label><input id="feedback-email" type="email" name="email" value={email} readOnly required className="w-full cursor-not-allowed border border-white/10 bg-white/[0.03] px-4 py-3 text-sm text-white/55 outline-none" /><p className="mt-2 text-[11px]">The email is already filled in 😁</p><ValidationError prefix="Email" field="email" errors={state.errors} /></div><div className="mt-6"><label htmlFor="feedback-message" className="mb-2 block text-xs font-medium text-white/65">Your message</label><textarea id="feedback-message" name="message" required minLength={5} placeholder="Describe the bug or share your idea..." className="min-h-48 w-full resize-y border border-white/10 bg-black/20 px-4 py-3 text-sm leading-6 text-white/80 outline-none focus:border-[var(--accent)]" /><ValidationError prefix="Message" field="message" errors={state.errors} /></div>{state.errors && <p className="mt-5 border-l-2 border-red-400/70 pl-3 text-xs text-red-300">Your message could not be sent. Please try again.</p>}<button type="submit" disabled={state.submitting || !email} className="mt-6 inline-flex items-center gap-2 bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-[#17130e] transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-50"><Send size={16} /> {state.submitting ? 'Sending...' : 'Submit feedback'}</button></form></div>;
}
