import { useEffect, useState } from 'react';
import type { AvPerformance, AvPerformanceUpdateInput } from '@/types';
import { useUpdateAvPerformance } from '@/features/performance/hooks/useAvPerformanceQueries';
import { Button, ImageUpload, Input, Modal, Textarea } from '@/shared/ui';
export default function EditAvPerformanceModal({ open, item, onClose }: { open: boolean; item: AvPerformance | null; onClose: () => void }) {
  const [form, setForm] = useState<AvPerformanceUpdateInput>({}); const mutation = useUpdateAvPerformance();
  useEffect(() => { if (item) setForm({ title: item.title, country: item.country, image_url: item.image_url, thumbnail_url: item.thumbnail_url ?? '', release_date: item.release_date ?? '', description: item.description ?? '' }); }, [item]);
  const set = (key: keyof AvPerformanceUpdateInput, value: string) => setForm((p) => ({ ...p, [key]: value }));
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!item || !form.title?.trim() || !form.image_url?.trim()) return; try { await mutation.mutateAsync({ id: item.id, data: { ...form, title: form.title.trim(), image_url: form.image_url.trim(), country: form.country?.trim() || 'Japan', thumbnail_url: form.thumbnail_url?.trim() || null, description: form.description?.trim() || null, release_date: form.release_date?.trim() || null } }); onClose(); } catch {} }
  return <Modal open={open} onClose={() => !mutation.isPending && onClose()} title={item?.title ?? 'Edit AV performance'} subtitle="Edit" footer={<><Button variant="ghost" onClick={onClose} disabled={mutation.isPending}>Cancel</Button><Button variant="primary" loading={mutation.isPending} onClick={(e) => submit(e as unknown as React.FormEvent)}>Save changes</Button></>}><form onSubmit={submit} style={{ display: 'flex', flexDirection: 'column', gap: 18 }}><Input id="edit-av-title" label="Title" value={form.title ?? ''} onChange={(e) => set('title', e.target.value)} required /><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}><Input id="edit-av-country" label="Country" value={form.country ?? ''} onChange={(e) => set('country', e.target.value)} /><Input id="edit-av-release-date" label="Release date" type="date" value={form.release_date ?? ''} onChange={(e) => set('release_date', e.target.value)} /></div><ImageUpload label="Primary image" value={form.image_url ?? ''} onChange={(url) => set('image_url', url)} /><ImageUpload label="Thumbnail" value={form.thumbnail_url ?? ''} onChange={(url) => set('thumbnail_url', url)} /><Textarea id="edit-av-description" label="Description" value={form.description ?? ''} onChange={(e) => set('description', e.target.value)} rows={3} /><button type="submit" style={{ display: 'none' }} /></form></Modal>;
}
