import { useState } from 'react';
import { Copy, Globe2, Loader2, Search } from 'lucide-react';
import { ToolCard, ToolTitle } from './ToolShell';

type IpDetails = { ip?: string; version?: string; city?: string; region?: string; country_name?: string; country_code?: string; postal?: string; latitude?: number; longitude?: number; timezone?: string; org?: string; asn?: string; error?: boolean; reason?: string };

export default function IpLookupTool() {
  const [value, setValue] = useState(''); const [details, setDetails] = useState<IpDetails | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const lookup = async () => { setLoading(true); setError(''); try { const target = value.trim(); const response = await fetch(target ? `https://ipapi.co/${encodeURIComponent(target)}/json/` : 'https://ipapi.co/json/'); const data = await response.json() as IpDetails; if (!response.ok || data.error) throw new Error(data.reason || `Lookup failed with HTTP ${response.status}`); setDetails(data); } catch (lookupError) { setDetails(null); setError(lookupError instanceof Error ? lookupError.message : 'Could not lookup this IP address.'); } finally { setLoading(false); } };
  const copy = async (text: string) => { await navigator.clipboard.writeText(text); };
  return <ToolCard><ToolTitle icon={Globe2} text="IP Address Lookup" subtitle="Inspect public IP, location, network, and timezone details from a single address." /><div className="mt-6 flex flex-col gap-3 sm:flex-row"><input value={value} onChange={(event) => setValue(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void lookup(); }} placeholder="Leave empty for your public IP or enter IPv4/IPv6" className="min-w-0 flex-1 border border-white/[0.08] bg-[#0d0d0a] px-4 py-3 text-sm text-white outline-none focus:border-[var(--accent-border)]" /><button type="button" onClick={() => void lookup()} disabled={loading} className="inline-flex items-center justify-center gap-2 bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-[#1b120e] disabled:opacity-50">{loading ? <Loader2 size={16} className="animate-spin" /> : <Search size={16} />} Lookup</button></div>{error && <p className="mt-4 border border-red-400/20 bg-red-400/5 p-3 text-xs text-red-300">{error}</p>}{details && <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['IP address', details.ip], ['Version', details.version], ['City', details.city], ['Region', details.region], ['Country', details.country_name ? `${details.country_name} (${details.country_code ?? ''})` : undefined], ['Postal code', details.postal], ['Coordinates', details.latitude !== undefined ? `${details.latitude}, ${details.longitude}` : undefined], ['Timezone', details.timezone], ['Network', details.org ? `${details.org}${details.asn ? ` (${details.asn})` : ''}` : undefined]].map(([label, data]) => <div key={label} className="border border-white/[0.08] bg-black/10 p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-white/35">{label}</p><div className="mt-2 flex items-start justify-between gap-2"><p className="break-words text-sm text-white/75">{data || 'Not available'}</p>{data && <button type="button" onClick={() => void copy(String(data))} className="text-white/35 hover:text-white" title="Copy"><Copy size={13} /></button>}</div></div>)}</div>}<p className="mt-5 text-xs text-white/30">Lookup uses ipapi.co and sends only the IP address you enter. Leave blank to detect your public IP.</p></ToolCard>;
}
