import { useMemo, useState } from 'react';
import { Copy, FileText, RefreshCw } from 'lucide-react';
import { ToolCard, ToolTitle } from './ToolShell';

type Mode = 'paragraphs' | 'sentences' | 'words';
const WORDS = 'lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi aliquip ex ea commodo consequat duis aute irure dolor reprehenderit voluptate velit esse cillum fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt culpa qui officia deserunt mollit anim id est laborum'.split(' ');
function sentence(length: number, offset: number) { const words = Array.from({ length }, (_, index) => WORDS[(offset + index) % WORDS.length]); return `${words.join(' ').replace(/^./, (letter) => letter.toUpperCase())}.`; }
function generate(mode: Mode, count: number, startWithLorem: boolean) { let cursor = startWithLorem ? 0 : 7; if (mode === 'words') return Array.from({ length: count }, (_, index) => WORDS[(cursor + index) % WORDS.length]).join(' ').replace(/^./, (letter) => letter.toUpperCase()) + '.'; const sentences = Array.from({ length: mode === 'sentences' ? count : count * 4 }, (_, index) => sentence(8 + ((index * 3) % 8), cursor + index * 5)); if (mode === 'sentences') return sentences.join(' '); const paragraphs: string[] = []; for (let index = 0; index < count; index += 1) paragraphs.push(sentences.slice(index * 4, index * 4 + 4).join(' ')); return paragraphs.join('\n\n'); }

export default function LoremIpsumTool() {
  const [mode, setMode] = useState<Mode>('paragraphs'); const [count, setCount] = useState(3); const [startWithLorem, setStartWithLorem] = useState(true); const [seed, setSeed] = useState(0); const output = useMemo(() => generate(mode, count, startWithLorem), [count, mode, seed, startWithLorem]);
  const copy = async () => { await navigator.clipboard.writeText(output); };
  return <ToolCard><ToolTitle icon={FileText} text="Lorem Ipsum Generator" subtitle="Generate clean placeholder copy for layouts, prototypes, and content previews." /><div className="mt-6 grid gap-5 lg:grid-cols-[280px_minmax(0,1fr)]"><aside className="border border-white/[0.08] bg-black/10 p-4"><label className="block text-xs text-white/50">Output type<select value={mode} onChange={(event) => setMode(event.target.value as Mode)} className="mt-2 w-full border border-white/[0.08] bg-[#0d0d0a] px-3 py-2.5 text-xs text-white outline-none"><option value="paragraphs">Paragraphs</option><option value="sentences">Sentences</option><option value="words">Words</option></select></label><label className="mt-4 block text-xs text-white/50">{mode === 'paragraphs' ? 'Paragraphs' : mode === 'sentences' ? 'Sentences' : 'Words'}<input type="number" min={1} max={30} value={count} onChange={(event) => setCount(Math.min(30, Math.max(1, Number(event.target.value) || 1)))} className="mt-2 w-full border border-white/[0.08] bg-[#0d0d0a] px-3 py-2.5 text-sm text-white outline-none" /></label><label className="mt-4 flex items-center gap-2 text-xs text-white/55"><input type="checkbox" checked={startWithLorem} onChange={(event) => setStartWithLorem(event.target.checked)} className="accent-[var(--accent)]" /> Start with “Lorem ipsum”</label><button type="button" onClick={() => setSeed((value) => value + 1)} className="mt-6 inline-flex w-full items-center justify-center gap-2 border border-white/10 px-3 py-2.5 text-xs text-white/60 hover:border-[var(--accent-border)] hover:text-white"><RefreshCw size={14} /> Generate new copy</button></aside><div><div className="mb-2 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-wider text-white/35">Generated text</span><button type="button" onClick={() => void copy()} className="inline-flex items-center gap-1.5 text-xs text-white/40 hover:text-white"><Copy size={13} /> Copy</button></div><textarea readOnly value={output} className="min-h-[360px] w-full resize-y border border-white/[0.08] bg-[#0d0d0a] p-4 text-sm leading-7 text-white/70 outline-none" /></div></div><p className="mt-5 text-xs text-white/30">Local generator · no content is sent to a server.</p></ToolCard>;
}
