import { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Clock3, Command, FileText, GitBranch, LayoutGrid, Search, X } from 'lucide-react';

type PaletteItem = { label: string; description: string; path: string; keywords: string[]; icon: typeof Command };
const ITEMS: PaletteItem[] = [
  { label: 'Git · Commit Generator', description: 'Generate commit messages from repository changes', path: '/tools/git?tab=commit-generator', keywords: ['git', 'commit', 'changes'], icon: GitBranch },
  { label: 'Git · History Graph', description: 'Explore branch and commit history', path: '/tools/git?tab=history-graph', keywords: ['git', 'history', 'graph', 'branch'], icon: GitBranch },
  { label: 'Markdown Studio', description: 'Write and preview GitHub-Flavored Markdown', path: '/tools/developer-tools?tab=markdown-studio', keywords: ['markdown', 'md', 'write', 'preview'], icon: FileText },
  { label: 'Developer Tools', description: 'Open JSON, JWT, Regex, Diff and other tools', path: '/tools/developer-tools', keywords: ['dev', 'developer', 'json', 'regex', 'diff', 'tools'], icon: LayoutGrid },
  { label: 'CSS Tools', description: 'Colors, gradients, scrollbars and minifiers', path: '/tools/css-tools', keywords: ['css', 'color', 'gradient'], icon: LayoutGrid },
  { label: 'AI Chat', description: 'Chat with Yolnoma AI', path: '/tools/ai-chat', keywords: ['ai', 'chat', 'assistant'], icon: Command },
  { label: 'Image Converter', description: 'Convert and batch process images', path: '/tools/image-converter', keywords: ['image', 'convert', 'png', 'webp'], icon: LayoutGrid },
  { label: 'Archive Explorer', description: 'Browse and extract archive files', path: '/tools/archive-explorer', keywords: ['archive', 'zip', 'extract'], icon: LayoutGrid },
  { label: 'Port Scanner', description: 'Inspect local and network ports', path: '/tools/port-scanner', keywords: ['port', 'network', 'scan'], icon: LayoutGrid },
  { label: 'Steam SAM', description: 'Inspect Steam achievements and stats', path: '/tools/steam/sam', keywords: ['steam', 'achievement', 'games'], icon: LayoutGrid },
];
const RECENT_KEY = 'yolnoma.palette.recent';

function readRecent() { try { return JSON.parse(localStorage.getItem(RECENT_KEY) || '[]') as string[]; } catch { return []; } }
function remember(path: string) { const next = [path, ...readRecent().filter((item) => item !== path)].slice(0, 6); localStorage.setItem(RECENT_KEY, JSON.stringify(next)); }

export default function CommandPalette() {
  const navigate = useNavigate(); const location = useLocation(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const [recent, setRecent] = useState<string[]>(readRecent); const [selected, setSelected] = useState(0);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (event.altKey && event.code === 'Space') { event.preventDefault(); setOpen(true); setQuery(''); setSelected(0); } if (event.key === 'Escape') setOpen(false); }; const onTray = () => { setOpen(true); setQuery(''); setSelected(0); }; window.addEventListener('keydown', onKey); window.addEventListener('yolnoma:palette-open', onTray); return () => { window.removeEventListener('keydown', onKey); window.removeEventListener('yolnoma:palette-open', onTray); }; }, []);
  useEffect(() => { setOpen(false); }, [location.pathname, location.search]);
  const results = useMemo(() => { const term = query.trim().toLowerCase(); const filtered = ITEMS.filter((item) => !term || `${item.label} ${item.description} ${item.keywords.join(' ')}`.toLowerCase().includes(term)); if (term) return filtered; const recentItems = recent.map((path) => ITEMS.find((item) => item.path === path)).filter((item): item is PaletteItem => Boolean(item)); return [...recentItems, ...filtered.filter((item) => !recent.includes(item.path))]; }, [query, recent]);
  const choose = (item: PaletteItem) => { remember(item.path); setRecent(readRecent()); window.dispatchEvent(new CustomEvent('yolnoma:palette-focus', { detail: true })); navigate(item.path); setOpen(false); };
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'ArrowDown') { event.preventDefault(); setSelected((value) => Math.min(value + 1, Math.max(0, results.length - 1))); } if (event.key === 'ArrowUp') { event.preventDefault(); setSelected((value) => Math.max(0, value - 1)); } if (event.key === 'Enter' && results[selected]) { event.preventDefault(); choose(results[selected]); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [open, results, selected]);
  if (!open) return null;
  return <div className="fixed inset-0 z-[100] flex items-start justify-center bg-black/65 px-4 pt-[13vh]" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false); }}><section className="w-full max-w-2xl overflow-hidden border border-white/15 bg-[#17130f] shadow-2xl" role="dialog" aria-modal="true" aria-label="Yolnoma command palette"><div className="flex items-center gap-3 border-b border-white/[0.09] px-4"><Search size={18} className="text-[var(--accent)]" /><input autoFocus value={query} onChange={(event) => { setQuery(event.target.value); setSelected(0); }} placeholder="Search tools, pages, and commands…" className="min-w-0 flex-1 bg-transparent py-4 text-sm text-white outline-none placeholder:text-white/30" /><kbd className="border border-white/10 px-2 py-1 text-[10px] text-white/30">ESC</kbd><button type="button" onClick={() => setOpen(false)} className="text-white/35 hover:text-white"><X size={16} /></button></div><div className="max-h-[min(60vh,520px)] overflow-y-auto p-2">{results.length ? results.map((item, index) => { const Icon = item.icon; return <button key={item.path} type="button" onClick={() => choose(item)} className={`flex w-full items-center gap-3 px-3 py-3 text-left ${index === selected ? 'bg-[var(--accent-dim)] text-white' : 'text-white/65 hover:bg-white/[0.05]'}`}><Icon size={17} className={index === selected ? 'text-[var(--accent)]' : 'text-white/35'} /><span className="min-w-0 flex-1"><span className="block text-sm">{item.label}</span><span className="mt-0.5 block truncate text-xs text-white/35">{item.description}</span></span>{!query && recent.includes(item.path) && <Clock3 size={13} className="text-white/25" />}</button>; }) : <p className="px-3 py-10 text-center text-sm text-white/35">No matching tool or page</p>}</div><div className="flex items-center justify-between border-t border-white/[0.08] px-4 py-2 text-[10px] text-white/25"><span><kbd className="mr-1 border border-white/10 px-1">↑↓</kbd> navigate <kbd className="mx-1 border border-white/10 px-1">Enter</kbd> open</span><span>Alt + Space to open</span></div></section></div>;
}
